### ISSUE TITLE
Usability improvement

### ISSUE THREAD

**Issue by apete** [lessthanoptimal/Java-Matrix-Benchmark#14]
When a case takes very long messages like these get printed periodically:

Master is still alive: Mon May 21 07:34:11 UTC 2018  Press 'q' and enter to quit. 66%

It would be much appreciated if this log statement could include info about what we're waiting for (library, operation, size) and perhaps when that was started.

**Comment by lessthanoptimal** [comment]
I've partially added that request. It says what is being processed but not when the test started. I'll add that later. The code has been pushed but not tested. I'm running a full --Quick with a max time per individual test of 1hr as a way to test all the recent changes. The new code might run faster since it will know when it can abort a test that's taking too long better.

**Comment by lessthanoptimal** [comment]
Just checked to benchmark and it appears to be working.  You can also specify memory in gigabytes now.
